# 图片生成服务配置
# 请在 Web 界面的"设置"页面中配置 API Key
active_provider: default
providers:
  default:
    api_key: "d48b6cb0-362b-40d6-bbde-9d2662d851a2"
    base_url: https://ark.cn-beijing.volces.com/api/v3
    high_concurrency: false
    model: doubao-seedream-4-5-251128
    type: image_api
